### ISSUE TITLE
Template render error: (unknown path) [Line 1, Column 126]   unexpected token: }}

### ISSUE THREAD

**Issue by youngjuning** [youngjuning/youngjuning.github.io#23]
## 案发现场

```
Template render error: (unknown path) [Line 1, Column 126]
  unexpected token: }}
    at Object.exports.prettifyError (E:\youngjuning\youngjuning.github.io\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (E:\youngjuning\youngjuning.github.io\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (E:\youngjuning\youngjuning.github.io\node_modules\nunjucks\src\environment.js:327:21)
    at E:\youngjuning\youngjuning.github.io\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:79:10)

    at Tag.render (E:\youngjuning\youngjuning.github.io\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\youngjuning\youngjuning.github.io\node_modules\hexo\lib\hexo\post.js:266:16)
    at E:\youngjuning\youngjuning.github.io\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\youngjuning\youngjuning.github.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
```

**Comment by youngjuning** [comment]
## 问题解决

标题就可以定位错误：

> 模板渲染错误：未知的符号：`}}`

**Comment by youngjuning** [comment]
## 问题解决

把 `{{}}`删掉就行，可以用 `双大括号` 表示
